[package]
name = "hdbconnect"
version = "0.21.4"
authors = ["emabee <meinolf.block@sap.com>","Pascal Seitz <pascal.seitz@gmail.com>"]
edition = "2018"
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/emabee/rust-hdbconnect"
documentation = "https://docs.rs/hdbconnect/"

description = "A pure rust driver for SAP HANA(TM)"
keywords = ["relational", "database", "driver", "serde", "HANA"]
categories = ["database"]
include = ["src/**/*", "LICENSE-*", "README.md", "CHANGELOG.md"]

[package.metadata.docs.rs]
all-features = false

[features]
default = []
alpha_routing = []

[dependencies]
bigdecimal = {version = "0.1", features = ["serde"]}
byteorder = "1.3"
cesu8 = "1.1"
chrono = { version = "0.4", features = ["serde"] }
#dist_tx = {path = "../dist_tx"}
dist_tx = "0.2"
hex = "0.4"
hmac = "0.9.0"
lazy_static = "1.4.0"
log = "0.4"
num = "0.2"
pbkdf2 = {version = "0.5.0", default-features = false}
r2d2 = "0.8"
rand = "0.7"
rustls = {version = "0.18", features = ["dangerous_configuration"]}
secstr = "0.4"
serde = { version = "1.0", features = ["derive"] }
#serde_db = { path = "../serde_db" }
serde_db = "0.9"
serde_json = "1.0"
sha2 = "0.9.0"
thiserror="1.0"
url = "2.1"
username = "0.2"
vec_map = "0.8"
webpki = "0.21"
webpki-roots = "0.20"

[dev-dependencies]
serde_bytes = "0.11"
# flexi_logger = {path = "../flexi_logger"}
flexi_logger = "0.15"
version-sync = "0.9"
# geo = "0.12"
# geo-types = "0.4.1"
# wkb = "*"
# wkb = { path = "../wkb" }
