[workspace]
members = [
    # main crates, published on crates.io
    "hdbconnect",
    "hdbconnect_async",

    # most of the code is here    
    "hdbconnect_impl",
]

default-members = [
    "hdbconnect",
    "hdbconnect_async",
]
