[workspace]
members = [
    # projection crates, should be used for consumption
    "hdbconnect",
    "hdbconnect_async",

    # the code is here, should not be consumed directly
    "hdbconnect_impl",
]
resolver = "2"

[workspace.package]
version = "0.29.0"
authors = [
    "emabee <meinolf.block@sap.com>",
    "Pascal Seitz <pascal.seitz@gmail.com>",
]
edition = "2021"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/emabee/rust-hdbconnect"
keywords = ["relational", "database", "driver", "HANA"]
categories = ["database"]
include = ["LICENSE-*", "README.md", "CHANGELOG.md"]
