[workspace]
members = [
    # projection crates, should be used
    "hdbconnect",
    "hdbconnect_async",

    # the code is here, should not be used
    "hdbconnect_impl",
]

# default-members = [
#     "hdbconnect",
#     "hdbconnect_async",
# ]
