[workspace]
members = [
    # projection crates, should be used for consumption
    "hdbconnect",
    "hdbconnect_async",

    # the code is here, should not be consumed directly
    "hdbconnect_impl",
]
